# These are supported funding model platforms

github: twaik # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: termux # Replace with a single Open Collective username
custom: https://termux.dev/donate
