name: Update Gradle Wrapper

on:
  schedule:
    - cron: "30 6 * * SAT"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
